////////////////////////////////INSERTS CATEGORIA_EMPLEADO

BEGIN

INSERT INTO CATEGORIA_EMPLEADO
VALUES ('CE-1', 'Cocinero');

INSERT INTO CATEGORIA_EMPLEADO
VALUES ('CE-2', 'Camarero');

INSERT INTO CATEGORIA_EMPLEADO
VALUES ('CE-3', 'Limpieza');

INSERT INTO CATEGORIA_EMPLEADO 
VALUES ('CE-4', 'Gerente');

EXCEPTION

WHEN OTHERS THEN

ROLLBACK;

END;
